### ISSUE TITLE
Illegal wire type for field Message.Field...

### ISSUE THREAD

**Issue by dcposch** [thibauts/node-castv2#35]
Version: 0.1.8

We're using castv2 in https://github.com/feross/webtorrent-desktop

We're seeing a lot of "illegal wire type" errors. 62 in the past 24 hours, from our telemetry. Here's an example:

```
Error: Illegal wire type for field Message.Field .extensions.api.cast_channel.CastMessage.payload_type: 6 (0 expected)
    at Error (native)
    at T.ProtoBuf.Reflect.FieldPrototype.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:3043:27)
    at T.ProtoBuf.Reflect.MessagePrototype.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:2462:49)
    at Function.Message.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:2190:41)
    at Object.parse (.../node_modules/castv2/lib/proto.js:22:34)
    at PacketStreamWrapper.onpacket (.../node_modules/castv2/lib/client.js:63:31)
    at emitOne (events.js:96:13)
    at PacketStreamWrapper.emit (events.js:188:7)
    at TLSSocket.<anonymous> (/Applications/WebTorrent.app/Contents/...
    ...
```

**Comment by dcposch** [comment]
@thibauts looks like a related error, also showing up in our telemetry:

```
Error: Illegal wire type for unknown field 12 in Message .extensions.api.cast_channel.CastMessage#decode: 7
    at Error (native)
    at T.ProtoBuf.Reflect.MessagePrototype.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:2455:39)
    at Function.Message.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:2190:41)
    at Object.parse (.../node_modules/castv2/lib/proto.js:22:34)
    at PacketStreamWrapper.onpacket (.../node_modules/castv2/lib/client.js:63:31)
    at emitOne (events.js:96:13)
    at PacketStreamWrapper.emit (events.js:188:7)
    at TLSSocket.<anonymous> (.../node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
```

Thanks for making castv2, it was surprisingly easy to add Chromecast support in WebTorrent Desktop!

**Comment by thibauts** [comment]
I have no clue where this could come from. Would it be possible to have a binary dump of the packet ? 

A recent try to upgrade protobufjs may have caused glitches in your builds. I've heard about a new version of the cast protocol too, but can't get my hand on the related .proto files.

Having the packets causing these errors could help investigate this bug in isolation. I don't have much time these days but I'll try to spare a few hours.

**Comment by dcposch** [comment]
Cool, Il try to add packet logging on error to our telemetry

**Comment by thibauts** [comment]
Closing for inactivity. Reopen as needed

**Comment by feross** [comment]
FWIW this is no longer one of our top 10 errors. Could still be happening, but it's not enough to make our top 10.
