### ISSUE TITLE
ReferenceError: val is not defined

### ISSUE THREAD

**Issue by dcposch** [thibauts/node-castv2#36]
Version: 0.1.8

We're using castv2 in https://github.com/feross/webtorrent-desktop

We're seeing a lot of this type of error:

```
ReferenceError: val is not defined
    at ByteBuffer.module.exports.ByteBufferPrototype.readVString (.../node_modules/bytebuffer/dist/ByteBufferNB.js:2015:67)
    at T.ProtoBuf.Reflect.FieldPrototype.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:3114:39)
    at T.ProtoBuf.Reflect.MessagePrototype.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:2462:49)
    at Function.Message.decode (.../node_modules/protobufjs/dist/ProtoBuf.js:2190:41)
    at Object.parse (.../node_modules/castv2/lib/proto.js:22:34)
    at PacketStreamWrapper.onpacket (.../node_modules/castv2/lib/client.js:63:31)
    at emitOne (events.js:96:13)
    at PacketStreamWrapper.emit (events.js:188:7)
   ...
```

**Comment by thibauts** [comment]
We've had a little [glitch](https://github.com/thibauts/node-castv2/issues/30) when trying to upgrade the protobufjs dependency a few days ago, could this be related ?

**Comment by feross** [comment]
It's possible. We'll ship a new version of the app in the next day or two and see if this error goes away in the error reports from the new version.

**Comment by thibauts** [comment]
Closing this as this is probably explained by the protobufjs upgrade. Reopen if needed.
